### ISSUE TITLE
File local don't load

### ISSUE THREAD

**Issue by DeeSouza** [TangoDev-it/cordova-plugin-vr-view-sample-app#2]
When try to play a video from local storage appear the error: **Error while loading video**.
If the video are in the **www** path, work fine.

I'm using the plugin **cordova-plugin-file** to get file video.

The line is commented.

```
this.file.checkFile(this.file.externalRootDirectory + 'Download/', 'Video.mp4').then((data) => { 
    if(window['VrView']) {
        console.log(options, fileVideo);
        window['VrView'].playVideo(fileVideo, options); // DON'T WORKING
    }
}).catch((err) => {
    console.log('Erro', err);
});
```

**Comment by manugando** [comment]
Hi! Please verify that the video path starts with the file schema: 
`file:///sdcard/my_video.mp4`
