### ISSUE TITLE
Match direction of user and stereo 360 image

### ISSUE THREAD

**Issue by cnothegger** [TangoDev-it/cordova-plugin-vr-view-sample-app#3]
The 360 image should point north when the user looks north. 

Currently it always starts on the same position and not depending on the direction the phone points to.

**Comment by manugando** [comment]
Hi! At the moment the plugin doesn't support that functionality and it's not in our roadmap :( I think that the link that you provided is related to Cardboard Camera App so those options doesn't take effect on the Vr View plugin.
