### ISSUE TITLE
Vimeo & Youtube support

### ISSUE THREAD

**Issue by naushrambo** [TangoDev-it/cordova-plugin-vr-view-sample-app#6]
On check vimeo and youtube url's it failed to load resource.

Sample Vimeo Video : https://player.vimeo.com/video/355120249
Sample Youtube Video : https://www.youtube.com/embed/rVLvBdhugeY

**Comment by manugando** [comment]
Hi, thanks for your interest in our plugin! Unfortunately at the moment our plugin doesn't support those video formats.
