### ISSUE TITLE
Unable to graft xml at selector 

### ISSUE THREAD

**Issue by ashishgehlot** [TangoDev-it/cordova-plugin-vr-view-sample-app#7]
I am getting error while installing plugin

Failed to install 'cordova-plugin-vr-view': Error: Unable to graft xml at selector "/manifest/uses-sdk" from "D:\Office\Medispark-VR\platforms\android\app\src\main\AndroidManifest.xml" during config install
    at ConfigFile_graft_child [as graft_child] (D:\Office\Medispark-VR\node_modules\cordova-common\src\ConfigChanges\ConfigFile.js:122:19)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (D:\Office\Medispark-VR\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:81:34)
    at munge_helper (D:\Office\Medispark-VR\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:252:14)
    at PlatformMunger.add_plugin_changes (D:\Office\Medispark-VR\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:159:12)
    at D:\Office\Medispark-VR\node_modules\cordova-common\src\PluginManager.js:123:29
    at _fulfilled (D:\Office\Medispark-VR\node_modules\q\q.js:834:54)
    at D:\Office\Medispark-VR\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (D:\Office\Medispark-VR\node_modules\q\q.js:796:13)
    at D:\Office\Medispark-VR\node_modules\q\q.js:857:14
Unable to graft xml at selector "/manifest/uses-sdk" from "D:\Office\Medispark-VR\platforms\android\app\src\main\AndroidManifest.xml" during config install
    at runSingle (D:\Office\Medispark-VR\node_modules\q\q.js:137:13)

**Cordova Version** : 9.0.0 (cordova-lib@9.0.1)
**Node** : v10.16.0
**Ionic** : 5.2.1

Here is plugin.xml content
<?xml version="1.0" encoding="utf-8"?>
<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
    id="cordova-plugin-vr-view"
    version="2.0.0">

    <name>VR View</name>

    <js-module src="www/vrview.js" name="vrview">
        <clobbers target="VrView" />
    </js-module>

    <platform name="android">
        <config-file target="res/xml/config.xml" parent="/*">
            <feature name="VrView">
                <param name="android-package" value="it.tangodev.cordovapluginvrview.VrView"/>
                <param name="onload" value="true" />
            </feature>
        </config-file>

        <config-file target="AndroidManifest.xml" parent="/manifest/application">
            <activity
                android:name="it.tangodev.cordovapluginvrview.VrVideoActivity"
                android:theme="@android:style/Theme.DeviceDefault.NoActionBar"></activity>
            <activity
                android:name="it.tangodev.cordovapluginvrview.VrPanoramaActivity"
                android:theme="@android:style/Theme.DeviceDefault.NoActionBar"></activity>
        </config-file>

        <edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
            <application android:largeHeap="true" />
        </edit-config>

        <edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
            <manifest xmlns:tools="http://schemas.android.com/tools" />
        </edit-config>

        <edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
            <uses-sdk tools:overrideLibrary="com.google.vr.widgets.video,com.google.vr.widgets.pano,com.google.vr.widgets.common" />
        </edit-config>

        <source-file src="src/android/java/it/tangodev/cordovapluginvrview/VrView.java" target-dir="src/it/tangodev/cordovapluginvrview/"/>
        <source-file src="src/android/java/it/tangodev/cordovapluginvrview/VrVideoActivity.java" target-dir="src/it/tangodev/cordovapluginvrview/"/>
        <source-file src="src/android/java/it/tangodev/cordovapluginvrview/VrPanoramaActivity.java" target-dir="src/it/tangodev/cordovapluginvrview/"/>
        <source-file src="src/android/java/it/tangodev/cordovapluginvrview/Utils.java" target-dir="src/it/tangodev/cordovapluginvrview/"/>

        <resource-file src="src/android/res/layout/vr_video_activity_layout.xml" target="res/layout/vr_video_activity_layout.xml" />
        <resource-file src="src/android/res/layout/vr_panorama_activity_layout.xml" target="res/layout/vr_panorama_activity_layout.xml" />
        <resource-file src="src/android/res/layout/vr_loading_indicator_layout.xml" target="res/layout/vr_loading_indicator_layout.xml" />
        <resource-file src="src/android/res/layout/vr_pause_indicator_layout.xml" target="res/layout/vr_pause_indicator_layout.xml" />
        <resource-file src="src/android/res/drawable/ic_play_white_48dp.png" target="res/drawable/ic_play_white_48dp.png" />

        <framework src="src/android/extra.gradle" custom="true" type="gradleReference" />
		<framework src="com.google.vr:sdk-videowidget:1.60.0" />
        <framework src="com.google.vr:sdk-panowidget:1.60.0" />
        <framework src="com.github.rahatarmanahmed:circularprogressview:2.5.0" />
    </platform>

    <platform name="ios">
        <dependency id="cordova-plugin-cocoapod-support" />

        <pods-config ios-min-version="8.0" uses-frameworks="true"/>

        <config-file target="config.xml" parent="/*">
            <feature name="VrView">
                <param name="ios-package" value="VrView" onload="true" />
            </feature>
        </config-file>

        <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
            <string>Used to scan QR codes</string>
        </config-file>

        <header-file src="src/ios/VrView.h" />
        <source-file src="src/ios/VrView.m" />
        <header-file src="src/ios/VrControllerViewController.h" />
        <source-file src="src/ios/VrControllerViewController.m" />
        <header-file src="src/ios/VideoVrVC.h" />
        <source-file src="src/ios/VideoVrVC.m" />
        <header-file src="src/ios/PanoramaVrVC.h" />
        <source-file src="src/ios/PanoramaVrVC.m" />

        <resource-file src="src/ios/play.png" />

        <pod id="GVRSDK" version="1.60.0" />
    </platform>

</plugin>

**Comment by manugando** [comment]
Hi! Please try to remove the platform from the project and add the platform again. Let me know if the problem gets solved!

**Comment by ashishgehlot** [comment]
After removing platform, plugin installed successfully but when I am trying to add android platform then this error came back. After some debugging I found that something is wrong with android manifest.xml so I commented these lines and it worked.


      <edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">  
             <uses-sdk tools:overrideLibrary="com.google.vr.widgets.video,com.google.vr.widgets.pano,com.google.vr.widgets.common" />  
 </edit-config>

**Comment by manugando** [comment]
Thanks for reporting your solution! :)
