### ISSUE TITLE
Stop video 

### ISSUE THREAD

**Issue by ashishgehlot** [TangoDev-it/cordova-plugin-vr-view-sample-app#8]
Hello, 

My requirement is to play videos in loop like video1->video2->video3->video1
As plugin doesn't have ability for video ended callback so is their any way to close running video via javascript.

Thanks

**Comment by manugando** [comment]
Hi! Unfortunately that's not possibile at the moment. You could try to use the events fired from the cordova activity to check when the activity gets hidden (when the video starts) and when is visibile again (when the video ends). Let me know if it works! :)
