### ISSUE TITLE
Does this plugin support live video?

### ISSUE THREAD

**Issue by GuangjieZHANG** [TangoDev-it/cordova-plugin-vr-view-sample-app#9]
Hello, I want to build an app with this excellent plugin which can play live vr-videos, but I've tried fill in url blinks and it doesn't work. Can we play a remote video in mp4 format and with rtmp protocol?
Looking forward to your answer, thanks!

**Comment by manugando** [comment]
Hi! Unfortunately the plugin doesn't support live videos :(
